files:
  - source: _locales/en/messages.json
    translation: /_locales/%two_letters_code%/%original_file_name%
  - source: amo/en/description.html
    translation: amo/%two_letters_code%/description.html
  - source: amo/en/summary.txt
    translation: amo/%two_letters_code%/summary.txt
